general.import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
term = "xterm-256color"

[window]
dynamic_title = true
padding = { x = 8, y = 6 }
opacity = 0.85

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
size = 7

[mouse]
hide_when_typing = true
