general.import = [
	"~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
term = "xterm-256color"

[window]
dynamic_title = true
padding = { x = 8, y = 6 }
opacity = 0.95

[font]
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Medium" } 
size = 8

[mouse]
hide_when_typing = true
