#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O HDMI-0 DP-3

bspc monitor HDMI-0 -d I II III IV V
bspc monitor DP-3 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#f0c6c6"
bspc config normal_border_color  "#939ab7"

bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/bspwm/scripts/init
