#!/bin/sh

handle() {
    case $1 in
        workspace*) if ! [[ "$1" =~ ^workspacev2 ]]; then
                echo $1 | rev | cut -d">" -f1 | rev
            fi ;;
    esac
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
