#!/bin/sh

handle() {
    case $1 in
        activewindow*) if ! [[ "$1" =~ ^activewindowv2 ]]; then
                echo $1 | cut -d ',' -f 2
            fi ;;
    esac
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
