#!/usr/bin/env bash

up_down() {
    case $1 in
	up)
	    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
	    ;;
	down)
	    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
	    ;;
	*)
	    ;;
    esac
}

up_down "$@"
