format = """
$directory\
$git_branch$git_commit$git_state$git_metrics$git_status\
$c$elixir$golang$lua$python$rust$zig\
$line_break\
$hostname$character
"""

[character]
format = '$symbol '
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'
vimcmd_symbol = '[~](green)'

